<?php
/**
 * Plugin adapter for whatsapp.
 * Generated by yaycommerce-init. Edit values as needed.
 */

defined( 'ABSPATH' ) || exit;

class WhatsappPluginAdapter {
    public function init(): void {
        ( new \WhatsappScoped\YayCommerce\AdminShell\Menu\ExternalPluginMenuAdapter( [
            'parent_menu'     => 'nta_whatsapp',
            'menu_title'      => 'WhatsApp',
            'menu_capability' => 'manage_options',
            'menu_slug'       => 'nta_whatsapp_recommended_plugins',
        ] ) )->init();
    }
}
